[package]
name = "observability2-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
# gRPC
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }

# OpenTelemetry core
opentelemetry = { version = "0.31", features = ["trace", "logs"] }
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
opentelemetry-stdout = { version = "0.31", features = ["trace", "logs"] }
opentelemetry-otlp = { version = "0.31", features = ["trace", "logs", "grpc-tonic"] }

# Bridges: tracing <-> OTel
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
tracing-opentelemetry = "0.32"
opentelemetry-appender-tracing = "0.31"
tonic-tracing-opentelemetry = { version = "0.32", features = ["tracing_level_info"] }
tower = "0.5"

[build-dependencies]
tonic-build = "0.14"
tonic-prost-build = "0.14"
